name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install mutagen pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller AudioTagFixer-Windows.spec --clean
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: AudioTagFixer-Windows
        path: dist/AudioTagFixer-Windows.exe 
